package com.euler;


/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


public class Evenfibonacci {
		 public static int efibonacci(int n) {
			 int a=1,b=2,sum=0;
			 do {
				 if(b%2==0) {
					 sum+=b;
				 }
				 int c=a+b;
				 a=b;
				 b=c;
			 }
			 while(b<n);
			 return sum;
			 
				}
			public static void main(String[] args) {
				// TODO Auto-generated method stub
		 System.out.println("EVEN FIBONACCI NUMBERS: "+efibonacci(4000000));
		 

		}
		
	}

